# Generated by Django 2.0 on 2018-06-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probe', '0002_auto_20180603_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snifferdetail',
            options={'ordering': ['-time']},
        ),
    ]
