# Generated by Django 2.0 on 2018-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probe', '0003_auto_20180614_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnifferEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=20)),
                ('mac', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
